### PR TITLE
Bringing the Linux port into better shape

### PR DESCRIPTION
**Pull request by pocak100**
This should make the game somewhat playable on Linux. I did my best to keep other OSes unaffected.

There are many issues left, though:

- The console is broken. The SDL keycodes need to be translated to whatever the console implementation expects. (ASCII?)
- The mouse aiming is strange. Small movements are exaggerated, especially at high sensitivity. Makes it hard to aim, and gives me motion sickness. Could be caused by some kind of rounding.
- It would be nice if the game adapted to different monitor aspect ratios and screen resolutions.
- Sound is loud and distorted.

### CODE REVIEW

**Comment by gbudny** [comment]
Hi

This is great!

How did you find out about this project?

**Comment by pocak100** [comment]
I sometimes lurk the Pyra forums.

OK, I just saw another pull request that's going to conflict with this one.

I guess I'll rebase on master, please hold on...

**Comment by gbudny** [comment]
Cool!

**Comment by brizzly** [comment]
Wow ! Impressive lets merge it!

**Comment by pocak100** [comment]
It's good to go.

There would have been a problem with missing mipmaps if we merged it as it was before.

**Comment by pocak100** [comment]
Darn, I hit the wrong button, sorry.

**Pull request merged**
